In [2]:
import numpy as np

# Datos

In [3]:
#next period stats Probabilities
m_prob=np.array([[0.7,0.3,0,0],
                [0,0.7,0.3,0],
                [0,0,0.6,0.4],
                [0,0,0,1]]
                )
#Reveneus por estados
states_reveneus=np.array([100,80,50,10])
c=-100

# Value Determination Equations

In [4]:
#funcion para obtener el valor de la ecuaciones
def Value_Determination_Equations(decisions,prob,descuento,costo,revenues):
    L=len(decisions)
    aux=np.zeros([L,L])
    B=np.zeros(L)
    for i in range(L):
        if decisions[i]:
            aux[i]=prob[0]
            B[i]=costo
        else:
            aux[i]=prob[i]
            B[i]=revenues[i]
    A = np.identity(L)-(descuento*aux)
    X = np.linalg.solve(A,B)
    return X
    

In [5]:
D=np.array([0,0,0,1])

Value_Determination_Equations(D,m_prob,0.9,c,states_reveneus)

array([690.23141846, 575.50231418, 492.35502314, 490.23141846])

In [6]:
D=np.array([0,0,1,1])

Value_Determination_Equations(D,m_prob,0.9,c,states_reveneus)

array([687.8125, 572.1875, 487.8125, 487.8125])

# Howard’s Policy Iteration Method

In [10]:
D=np.array([0,0,1,1])
V_D_E=Value_Determination_Equations(D,m_prob,0.9,c,states_reveneus)


def T_delta(prob,values,descuento,costo,revenues):
    L=len(values)
    T=np.zeros(L)
    #aux_1 siempre igual
    aux_1=costo+(descuento*sum(prob[0]*values))
    for i in range(L):
        aux_2=revenues[i]+(descuento*sum(prob[i]*values))
        T[i]=max(aux_1,aux_2)
    return T
        
        

In [11]:
Los_T=T_delta(m_prob,V_D_E,0.9,c,states_reveneus)

In [12]:
#Los_T == V_D_E
np.around(Los_T,4)==np.around(V_D_E,4)

array([ True,  True, False,  True])

In [14]:
val_Op=np.around(Los_T,4)==np.around(V_D_E,4)
val_Op

array([ True,  True, False,  True])

In [16]:
sum(val_Op)
len(val_Op)

4

In [26]:
def Search_OP(decisions,prob,descuento,costo,revenues):
    print('recurción')
    #(D,m_prob,descuento,c,states_reveneus)
    V_D_E = Value_Determination_Equations(decisions,prob,descuento,costo,revenues)
    Los_T=T_delta(prob,V_D_E,descuento,costo,revenues)
    val_Op=np.around(Los_T,4)==np.around(V_D_E,4)
    if(sum(val_Op)==len(val_Op)):
        return(decisions)
    else:
        for i in range(len(val_Op)):
            if (val_Op[i]!=True):
                if(decisions[i]==1):
                    decisions[i]=0
                else:
                    decisions[i]=1
        #For
        return(Search_OP(decisions,prob,descuento,costo,revenues))

In [29]:
D=np.array([1,1,1,1])
D_optimo=Search_OP(D,m_prob,0.9,c,states_reveneus)

recurción
recurción
recurción
recurción


In [30]:
D_optimo

array([0, 0, 0, 1])