In [1]:
import numpy as np

# Datos

In [2]:
#next period stats Probabilities
m_prob=np.array([[0.7,0.3,0,0],
                [0,0.7,0.3,0],
                [0,0,0.6,0.4],
                [0,0,0,1]]
                )
#Reveneus por estados
states_reveneus=np.array([100,80,50,10])
c=-100

# Value Determination Equations

In [10]:
#funcion para obtener el valor de la ecuaciones
def Value_Determination_Equations(decisions,prob,descuento,costo,revenues):
    L=len(decisions)
    aux=np.zeros([L,L])
    B=np.zeros(L)
    for i in range(L):
        if decisions[i]:
            aux[i]=prob[0]
            B[i]=costo
        else:
            aux[i]=prob[i]
            B[i]=revenues[i]
    A = np.identity(L)-(descuento*aux)
    X = np.linalg.solve(A,B)
    return X
    

In [11]:
D=np.array([0,0,0,1])

Value_Determination_Equations(D,m_prob,0.9,c,states_reveneus)

array([690.23141846, 575.50231418, 492.35502314, 490.23141846])

In [12]:
D=np.array([0,0,1,1])

Value_Determination_Equations(D,m_prob,0.9,c,states_reveneus)

array([687.8125, 572.1875, 487.8125, 487.8125])

# Howard’s Policy Iteration Method

In [6]:
D=np.array([0,0,1,1])
V_D_E=Value_Determination_Equations(D,m_prob,0.9,c,states_reveneus)

def T_delta(prob,values,descuento,costo,revenues):
    L=len(values)
    T=np.zeros(L)
    #aux_1 siempre igual
    aux_1=costo+(descuento*())
    for i in range(L):
        aux_2=reveneus[i]+(descuento*(prob[i]*values))
        
        

4

In [14]:
m_prob[2]*V_D_E

array([  0.    ,   0.    , 292.6875, 195.125 ])

In [15]:
sum(m_prob[2]*V_D_E)+50

537.8125000000005