In [1]:
import numpy as np

In [12]:
inicial=np.array([[0.37,-0.27,0,0],
                [0,0.37,-0.27,0],
                [0,0,0.46,-0.36],
                [-0.63,-0.27,0,1]])
B=np.array([100,80,50,-100])

In [8]:
A_inv = np.linalg.inv(inicial)
A_inv

array([[3.91930302, 3.38143207, 1.98475361, 0.7145113 ],
       [1.66719303, 4.63381432, 2.71984754, 0.97914511],
       [2.28467193, 2.64633814, 3.72719848, 1.34179145],
       [2.91930302, 3.38143207, 1.98475361, 1.7145113 ]])

In [10]:
A_inv@inicial

array([[1.00000000e+00, 7.39051256e-17, 1.59567431e-16, 1.11022302e-16],
       [4.78322044e-17, 1.00000000e+00, 2.77081199e-17, 3.33066907e-16],
       [1.47252026e-16, 3.38965931e-17, 1.00000000e+00, 2.22044605e-16],
       [8.78652204e-17, 1.84927428e-16, 5.74269132e-17, 1.00000000e+00]])

In [14]:
x_1=A_inv@B

In [16]:
x_2=np.linalg.solve(inicial,B)

In [17]:
inicial@x_1==B

array([False, False, False, False])

In [18]:
inicial@x_2==B

array([False, False,  True,  True])

In [19]:
x_1

array([690.23141846, 575.50231418, 492.35502314, 490.23141846])

In [20]:
x_2

array([690.23141846, 575.50231418, 492.35502314, 490.23141846])